---
# tasks file for docker

    - name: update all packages
      ansible.builtin.yum:
        name: '*'
        state: latest
 
    - name: remove old docker packages
      ansible.builtin.yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: removed
    
    - name: install yum utils
      ansible.builtin.yum:
        name: "yum-utils"
        state: latest
 
    - name: add docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
  
    - name: install docker
      ansible.builtin.package:
        name: docker-ce
        state: latest

    - name: add user ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes

    - name: start docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes